# Generated by Django 4.2.21 on 2025-05-31 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
