# Generated by Django 5.2.3 on 2025-06-12 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='kcal',
            new_name='kcal_per_unit',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='units',
            new_name='unit',
        ),
    ]
